services:
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - app-net

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      - ConnectionStrings__DefaultConnection=server=db;database=farmed;user=root;password=root;port=3306
    depends_on:
      - db
    networks:
      - app-net

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: farmed
    ports:
      - '3366:3306'
    volumes:
      - 'mysql-data:/var/lib/mysql'
      - './mysql/farmed.sql:/docker-entrypoint-initdb.d/farmed.sql'
    networks:
      - app-net
  
volumes:
  mysql-data:

networks:
  app-net: